#' Sample toy data to illustrate the package usage
#'
#' A dataset containing 1000 observations from two interval-censored data outcomes. The data are generated by the example shown in function \code{BiCase2_SimuDat}.
#'
#' \itemize{
#'   \item tu_1, tu_2 left boundary of the observation intervals
#'   \item tv_1, tv_2 right boundary of the observation intervals
#'   \item ind_1, ind_2 indicators of censoring types
#' }
#' @docType data
#' @name SampleDat_case2
#' @format A list of 2 items. T1: interval censored data from outcome 1; T2: interval censored data from outcome 2.
#'
NULL

